version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397745665.dkr.ecr.us-east-1.amazonaws.com
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t solanki-flask-app .
      - docker tag solanki-flask-app:latest 767397745665.dkr.ecr.us-east-1.amazonaws.com/solanki-flask-app:latest
  
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 767397745665.dkr.ecr.us-east-1.amazonaws.com/solanki-flask-app:latest
